### ISSUE TITLE
Use a JODC logo image as the fallback image for Team Members and Event Posters

### ISSUE THREAD

**Issue by AarKiMos** [JIITODC/website#230]
Currently we use a plain grey solid image as a fallback image for all the Team Members and Event posters. This image does not give an aesthetically pleasing view to the site. Visitors may get confused about the image not loading.
Using JODC image logo will be a good solution for this.

**Comment by MAZ12211** [comment]
I think I'm up for the task.
> Using JODC image logo will be a good solution for this.


Just to be sure, the JODC logo is that one?
![SharedScreenshot](https://user-images.githubusercontent.com/80357251/126871614-f0006924-7be0-489c-af51-73150f023a17.jpg)

**Comment by AarKiMos** [comment]
Sure
yes, that is the logo.

**Comment by MAZ12211** [comment]
Tried replacing the `Poster.png` with `jodcMascotWB.svg` on `EventComponent.svelte` & `TeamComponent.svelte`
Here's what it looks like on the event page:
![SharedScreenshot](https://user-images.githubusercontent.com/80357251/126905357-71d303c1-36e4-4771-9273-e16fbaf99a93.jpg)
It doesn't work on the Team page though for some reason. Do I have to open an issue to this one?

**Comment by AarKiMos** [comment]
This looks great on event page. 
Pro tip: if you open a pull request with your commits so far, our CI setup will create a preview, that we can checkout.

**Comment by AarKiMos** [comment]
This looks good so far. 
The reason it is not working for is that the old 'poster' image has been hardcoded into  /static/data/*Team.json files. 
removing "imgSrc": "Photos/webp/Poster.webp", OR "imgSrc": "Photos/Poster.png"  from these files shoud do the trick.

**Comment by MAZ12211** [comment]
Aight, I deleted `"imgSrc": "Photos/webp/Poster.webp"` and `"imgSrc": "Photos/Poster.png"` lines on `Team.json` files.
