### ISSUE TITLE
add discord to social media links on the landing page

### ISSUE THREAD

**Issue by humancalico** [JIITODC/website#82]
file to be changed: `src/routes/index.svelte`
Discord Link: https://discord.gg/RMSZtzr

**Comment by Yashs911** [comment]
@humancalico I would like to work on this

**Comment by Yashs911** [comment]
@humancalico Can you please guide me on how to add the discord logo?

**Comment by Yashs911** [comment]
![aaa](https://user-images.githubusercontent.com/64412143/97185946-b4d8c280-17c6-11eb-8380-8ffbd7eeaaf6.JPG)
logo size is too small. I downloaded it from FA and used the path to create a discord var.

**Comment by Yashs911** [comment]
@humancalico Can u please help me with this issue

**Comment by humancalico** [comment]
Can you reopen the PR? @Yashs911

**Comment by Yashs911** [comment]
@humancalico Actually I deleted that branch. Can you guide me on how to add the discord logo?

**Comment by humancalico** [comment]
@Yashs911 It's kinda difficult to tell what's going wrong without looking at the code.

**Comment by Yashs911** [comment]
@humancalico I just want to know the procedure how to add the discord logo.

**Comment by humancalico** [comment]
@Yashs911 as a rule of thumb: if you're working on something and are stuck just open a PR and ping contributors there. Someone would help you there. It doesn't matter if the code is bad or not finished.
